// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {ZcashAddress} from "../src/ZcashAddress.sol";

/// @dev Wrapper so we can assert on reverts from an internal library function.
contract ZcashAddressHarness {
    function validate(string memory encoded) external pure returns (bytes2, bytes20) {
        return ZcashAddress.validate(encoded);
    }

    function isValid(string memory encoded) external pure returns (bool) {
        return ZcashAddress.isValid(encoded);
    }
}

/**
 * Vectors were generated by Base58Check-encoding known version+hash160 pairs
 * (see script/gen-taddr.js), not transcribed from memory, so the expected
 * hash160 values below are authoritative.
 */
contract ZcashAddressTest is Test {
    ZcashAddressHarness internal harness;

    string constant T1_A = "t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX56U";
    string constant T1_B = "t1YWKgvpE5sqoXnWGsneB3mmmZvcPL5VBub";
    string constant T1_C = "t1Y2ngZYjZheg5S55h84ZaYtSf7XE6FPbBq";
    string constant T3_A = "t3RGLfnZuS1KC8NXizVcdWf5JRkonfbwKdd";
    string constant T3_B = "t3QiRNUGMjybE5yQieHaxwtZvkbh1QqydiT";
    string constant T1_ZEROS = "t1Hsc1LR8yKnbbe3twRp88p6vFfC5t7DLbs";
    string constant T1_FFS = "t1hDCzSiRgWFUR5Byxr9ScwNhtAT2UTqDNs";

    string constant BAD_VERSION = "tW7rHp81WDV6iZn42EqG6KRi6Kh4Uq5jCu7";
    string constant TESTNET_ADDR = "tmPqq3aWjZhqMwnSnpioaFM7xJaXZFpAA1Z";

    function setUp() public {
        harness = new ZcashAddressHarness();
    }

    function test_acceptsP2pkhAndRecoversHash160() public view {
        (bytes2 version, bytes20 payload) = harness.validate(T1_A);
        assertEq(version, ZcashAddress.VERSION_P2PKH, "version");
        assertEq(payload, bytes20(hex"a0f7733c65c22914cd657ce95ecb3c9e653ac07e"), "hash160");
    }

    function test_acceptsAdditionalP2pkhVectors() public view {
        (, bytes20 b) = harness.validate(T1_B);
        assertEq(b, bytes20(hex"a08387cfa5b3d238c3d549dfa9a2f78e9254627a"));
        (, bytes20 c) = harness.validate(T1_C);
        assertEq(c, bytes20(hex"9b4e6ab16c31d29123aa30271ed64fe75d0c1183"));
    }

    function test_acceptsP2sh() public view {
        (bytes2 version, bytes20 payload) = harness.validate(T3_A);
        assertEq(version, ZcashAddress.VERSION_P2SH, "version");
        assertEq(payload, bytes20(hex"49843c5d4301f66a635d16d9c78da6ac735748f6"), "hash160");

        (bytes2 v2,) = harness.validate(T3_B);
        assertEq(v2, ZcashAddress.VERSION_P2SH);
    }

    /// @dev Interior zero bytes are where a naive big-integer decoder typically breaks.
    function test_acceptsAllZeroPayload() public view {
        (, bytes20 payload) = harness.validate(T1_ZEROS);
        assertEq(payload, bytes20(0));
    }

    function test_acceptsAllOnesPayload() public view {
        (, bytes20 payload) = harness.validate(T1_FFS);
        assertEq(payload, bytes20(hex"ffffffffffffffffffffffffffffffffffffffff"));
    }

    function test_rejectsSingleCharacterTypo() public {
        // Swap the final character; the Base58Check checksum must catch it.
        string memory typo = "t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX56V";
        vm.expectRevert(ZcashAddress.BadChecksum.selector);
        harness.validate(typo);
    }

    function test_rejectsTransposedCharacters() public {
        // "...X56U" -> "...X65U": a transposition, the classic manual-entry error.
        string memory transposed = "t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX65U";
        vm.expectRevert(ZcashAddress.BadChecksum.selector);
        harness.validate(transposed);
    }

    function test_rejectsUnsupportedVersionPrefix() public {
        vm.expectRevert(
            abi.encodeWithSelector(ZcashAddress.UnsupportedVersion.selector, bytes2(0x1cff))
        );
        harness.validate(BAD_VERSION);
    }

    /// @dev A well-formed testnet address must not be accepted for mainnet payouts.
    function test_rejectsTestnetAddress() public {
        vm.expectRevert(
            abi.encodeWithSelector(ZcashAddress.UnsupportedVersion.selector, bytes2(0x1d25))
        );
        harness.validate(TESTNET_ADDR);
    }

    function test_rejectsWrongLength() public {
        vm.expectRevert(abi.encodeWithSelector(ZcashAddress.InvalidLength.selector, 34));
        harness.validate("t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX56");

        vm.expectRevert(abi.encodeWithSelector(ZcashAddress.InvalidLength.selector, 36));
        harness.validate("t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX56UU");

        vm.expectRevert(abi.encodeWithSelector(ZcashAddress.InvalidLength.selector, 0));
        harness.validate("");
    }

    /// @dev `0`, `O`, `I` and `l` are excluded from Base58 precisely because they are confusable.
    function test_rejectsCharactersOutsideAlphabet() public {
        string[4] memory confusable = [
            "t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX560", // '0'
            "t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX56O", // 'O'
            "t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX56I", // 'I'
            "t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX56l" // 'l'
        ];
        for (uint256 i = 0; i < confusable.length; ++i) {
            vm.expectRevert(ZcashAddress.InvalidCharacter.selector);
            harness.validate(confusable[i]);
        }
    }

    function test_rejectsShieldedAndUnifiedAddresses() public {
        // Shielded (zs...) and unified (u1...) addresses are Bech32/Bech32m and far longer,
        // so they fail on length before any checksum work.
        vm.expectRevert();
        harness.validate("zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9sly");
        vm.expectRevert();
        harness.validate("u1l8xunezsvhq8fgzfl7404m450nwnd76zshscn6nfys7vyz2ywyh4cc5daaq0c7q2su5lqfh23sp7fkyy6c");
    }

    function test_isValidMirrorsValidateWithoutReverting() public view {
        assertTrue(harness.isValid(T1_A));
        assertTrue(harness.isValid(T3_A));
        assertFalse(harness.isValid(BAD_VERSION));
        assertFalse(harness.isValid("t1YYiZAZNamauF6bfzCUc7mBaDZdaMmX56V"));
        assertFalse(harness.isValid("not-an-address"));
    }

    /// @dev No input should ever panic or consume unbounded gas.
    function testFuzz_neverRevertsUnexpectedly(string memory input) public view {
        harness.isValid(input);
    }

    /// @dev Mutating any single character of a valid address must invalidate it.
    function testFuzz_anyMutationBreaksChecksum(uint8 position, uint8 replacement) public view {
        bytes memory addr = bytes(T1_A);
        position = uint8(bound(position, 2, 34)); // leave the "t1" prefix intact
        bytes1 substitute = bytes1(replacement);
        if (substitute == addr[position]) return;

        addr[position] = substitute;
        assertFalse(harness.isValid(string(addr)));
    }
}
